import { Match } from "../types/match";

export const dummyMatches: Match[] = [
  {
    id: 1,
    sportId: 1,
    sportName: 'NBA',
    tournamentName: 'NBA',
    homeTeam: 'Portland Trail Blazers',
    awayTeam: 'Golden State Warriors',
    homeLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/por.png',
    awayLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/gs.png',
    startTimeISO: '2026-01-14T05:00:00Z',
  },
  {
    id: 2,
    sportId: 2,
    sportName: 'NRL',
    tournamentName: 'NRL',
    homeTeam: 'St. George Illawarra',
    awayTeam: 'Canterbury Bulldogs',
    homeLogo: 'https://a.espncdn.com/i/teamlogos/nrl/500/sgi.png',
    awayLogo: 'https://a.espncdn.com/i/teamlogos/nrl/500/cby.png',
    startTimeISO: '2026-01-14T05:15:00Z',
    hasTips: true,
  },
  {
    id: 3,
    sportId: 3,
    sportName: 'AFL',
    tournamentName: 'AFL',
    homeTeam: 'GWS Giants',
    awayTeam: 'North Melbourne',
    homeLogo: 'https://a.espncdn.com/i/teamlogos/afl/500/gws.png',
    awayLogo: 'https://a.espncdn.com/i/teamlogos/afl/500/nm.png',
    startTimeISO: '2026-01-14T05:20:00Z',
    hasTips: true,
  },
  {
    id: 4,
    sportId: 4,
    sportName: 'Australian Open',
    tournamentName: 'AO',
    homeTeam: 'Djokovic N.',
    awayTeam: 'Zverev A.',
    homeLogo: 'https://a.espncdn.com/i/headshots/tennis/players/full/296.png',
    awayLogo: 'https://a.espncdn.com/i/headshots/tennis/players/full/148.png',
    startTimeISO: '2026-01-14T05:25:00Z',
  },
  {
    id: 5,
    sportId: 5,
    sportName: 'NFL',
    tournamentName: 'NFL',
    homeTeam: 'San Francisco 49ers',
    awayTeam: 'Detroit Lions',
    homeLogo: 'https://a.espncdn.com/i/teamlogos/nfl/500/sf.png',
    awayLogo: 'https://a.espncdn.com/i/teamlogos/nfl/500/det.png',
    startTimeISO: '2026-01-14T05:05:00Z',
  },
  {
    id: 6,
    sportId: 8,
    sportName: 'EPL',
    tournamentName: 'EPL',
    homeTeam: 'Arsenal FC',
    awayTeam: 'Leicester FC',
    homeLogo: 'https://a.espncdn.com/i/teamlogos/soccer/500/359.png',
    awayLogo: 'https://a.espncdn.com/i/teamlogos/soccer/500/375.png',
    startTimeISO: '2026-01-14T01:20:00Z',
    hasTips: true,
  },
  {
    id: 7,
    sportId: 8,
    sportName: 'EPL',
    tournamentName: 'EPL',
    homeTeam: 'Chelsea',
    awayTeam: 'Liverpool',
    homeLogo: 'https://a.espncdn.com/i/teamlogos/soccer/500/363.png',
    awayLogo: 'https://a.espncdn.com/i/teamlogos/soccer/500/364.png',
    startTimeISO: '2026-01-14T02:30:00Z',
  },
  {
    id: 8,
    sportId: 8,
    sportName: 'EPL',
    tournamentName: 'EPL',
    homeTeam: 'Man City',
    awayTeam: 'Tottenham',
    homeLogo: 'https://a.espncdn.com/i/teamlogos/soccer/500/382.png',
    awayLogo: 'https://a.espncdn.com/i/teamlogos/soccer/500/367.png',
    startTimeISO: '2026-01-14T03:00:00Z',
  },
  {
    id: 9,
    sportId: 1,
    sportName: 'NBA',
    tournamentName: 'NBA',
    homeTeam: 'Lakers',
    awayTeam: 'Bulls',
    homeLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/lal.png',
    awayLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/chi.png',
    startTimeISO: '2026-01-14T06:00:00Z',
  },
  {
    id: 10,
    sportId: 5,
    sportName: 'NFL',
    tournamentName: 'NFL',
    homeTeam: 'Chiefs',
    awayTeam: 'Packers',
    homeLogo: 'https://a.espncdn.com/i/teamlogos/nfl/500/kc.png',
    awayLogo: 'https://a.espncdn.com/i/teamlogos/nfl/500/gb.png',
    startTimeISO: '2026-01-14T07:00:00Z',
  },
];
